const fmt=(x,d=3)=>Number.isFinite(x)?Math.abs(x)>0&&Math.abs(x)<.001?x.toExponential(2):x.toFixed(d):'—';
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function bars(items,{signed=false}={}){const max=Math.max(1e-20,...items.map(x=>Math.abs(x.value)));return `<div class="live-bars">${items.map(x=>`<div><span>${escape(x.label)}</span><i style="width:${Math.max(.3,Math.abs(x.value)/max*100)}%;background:${signed&&x.value<0?'#d3a0ef':'#78b9ff'}"></i><b>${fmt(x.value)}</b></div>`).join('')}</div>`;}
function spark(values,selected=-1){const w=320,h=75,max=Math.max(1,...values.filter(Number.isFinite));return `<svg viewBox="0 0 ${w} ${h}" role="img" aria-label="Per-byte surprise in bits"><path d="${values.map((v,i)=>`${i?'L':'M'}${i/Math.max(1,values.length-1)*w},${h-5-v/max*(h-15)}`).join(' ')}" fill="none" stroke="#78b9ff" stroke-width="1.5"/>${selected>=0?`<line x1="${selected/Math.max(1,values.length-1)*w}" x2="${selected/Math.max(1,values.length-1)*w}" y1="0" y2="75" stroke="#b2f576"/>`:''}<text x="4" y="12" fill="#b9c8d8" font-size="10">0–${fmt(max,1)} bits · position 1–${values.length}</text></svg>`;}
export function diagnosticHTML(topic,c){
 if(!c)return '';const r=c.row,s=c.state?.latest;let body='';
 if(c.plot){body=`<p>Nearest retained point: ${escape(c.plot.xLabel)} <b>${c.plot.x}</b>. ${escape(c.plot.unit)}.</p>`+bars(c.plot.values.map((x,i)=>({label:x.label||`Series ${i+1}`,value:x.y})));}
 else if(r&&['gradient-reward','gradients','absolute-value','preconditioner','directional-derivative','advantage','policy-gradient','expert-iteration','importance'].includes(topic)){
  const a=r.alignment;body=`<p>This program’s active reward: <b>${fmt(r.reward,5)}</b>${c.state?.config.mode==='difficulty'?' (difficulty ablation: loss in nats, not alignment)':''}.</p>`;
  if(a)body+=`<p>Signed gradient dot direction: ${fmt(a.signed,6)}; absolute value: ${fmt(Math.abs(a.signed),6)}. Positive terms sum to ${fmt(a.positive)}; negative terms sum to ${fmt(a.negative)}. They can cancel before taking the absolute value.</p>${bars(a.blocks.map(x=>({label:x.name,value:x.contribution})),{signed:true})}<p>Gradient norm ${fmt(a.gradientNorm)} · direction norm ${fmt(a.directionNorm)} · cosine ${fmt(a.cosine)}.</p>`;
  if(s)body+=`<p>Captured batch mean ${fmt(s.reward,5)}; standard deviation ${fmt(s.rewardStd,5)}. Historical reference: θ${s.lookback}, compared with pre-update θ${s.round-1}.</p>`;
  if(r.policy)body+=`<p>Normalized advantage with KL: ${fmt(r.policy.advantage)} · importance ratio: ${fmt(r.policy.ratio)} · policy-gradient weight: ${fmt(r.policy.pg)} · expert-iteration weight: ${fmt(r.policy.ei)}. ${r.oldLogp===null?'Mutation proposal: excluded from policy gradients.':''}</p>`;
 }else if(r&&['teacher-forcing','bpb','cross-entropy','padding','emissions','program','machine'].includes(topic)){
  body=`<p><b>${r.emitted}</b> emitted + <b>${r.output.length-r.emitted}</b> padding = ${r.output.length} training bytes. ${fmt(100*r.emitted/r.output.length,1)}% emitted. Mean surprise: ${fmt(r.loss)} bits/byte.</p>`;
  if(c.byteIndex!==undefined){const i=c.byteIndex;body+=`<p>Position ${i+1}: actual byte <b>${r.output[i]}</b> (${i<r.emitted?'emitted':'padding'}). Highest-probability prediction: <b>${r.predictions[i]}</b>. Probability assigned to the actual byte: <b>${fmt(100*2**-r.surprise[i],4)}%</b>; surprise −log₂(p) = ${fmt(r.surprise[i])} bits.</p>`;}
  if(r.surprise)body+=spark(r.surprise,c.byteIndex)+`<p>Actual byte positions on the horizontal axis; surprise on the vertical axis. The learner was given true preceding bytes.</p>`;
  if(topic==='program'||topic==='machine')body+=`<p>${r.steps.toLocaleString()} primitive steps; ${escape(r.reason)}. Select the row and open the execution viewer to follow the instruction pointer.</p>`;
 }else if(s&&['reward-statistics','advantage','pool','zero-reward'].includes(topic)){
  body=`<p>Batch mean ${fmt(s.reward,5)} · population standard deviation ${fmt(s.rewardStd,5)} · min ${fmt(s.rewardMin,5)} · max ${fmt(s.rewardMax,5)}.</p>`+bars(s.rows.map((r,i)=>({label:`Program ${i+1} · ${r.source}`,value:r.reward})));
 }else if(s&&['emissions','padding','diagnostics'].includes(topic))body=`<p>This batch contains ${s.rows.reduce((n,r)=>n+r.emitted,0)} emitted bytes out of ${s.rows.reduce((n,r)=>n+r.output.length,0)} total bytes: ${fmt(100*s.emittedFraction,1)}%. Loss on emitted bytes is ${fmt(s.emittedLoss)} bits/byte; loss on padding is ${fmt(s.padLoss)} bits/byte. Different units measure different things.</p>`;
 else if(s&&topic==='archive')body=`<p>${s.niches} of 36 niches are occupied after this round. Niches combine maximum executed loop depth (0–8, capped) with four source-body-length ranges (≤8, 9–16, 17–32, >32). Up to 8 programs survive per niche.</p><div class="coverage-track"><i style="width:${100*s.niches/36}%"></i></div>`;
 else if(s&&topic==='exploration')body=`<p>Fresh-prefix instruction entropy: ${fmt(s.generatorEntropy)} / ${fmt(Math.log2(19))} bits. Distinct emitted byte values: ${s.uniqueBytes}/256. These describe exploration, not transfer.</p>`;
 else if(s&&topic==='history')body=`<p>This batch was scored at learner state θ${s.round-1}, using historical weights θ${s.lookback}. The reference is floor((${s.round}-1)/2), before the round’s learner update.</p>`;
 else if(c.state&&topic==='round')body=`<p>Round ${c.state.round} has completed. One round samples ${c.state.config.pool} programs, scores each, performs one learner update and one generator update. The control, if enabled, has its own equally sized learner batch.</p>`;
 else if(c.state&&['transformer','attention','context'].includes(topic)){const q=c.state.config;body=`<p>Current run: ${q.layers??1} layer(s), width ${q.dim}, ${q.heads??2} attention heads of width ${q.dim/(q.heads??2)}, feed-forward width ${q.dim*(q.ffMultiplier??2)}. Learner context ${q.context} bytes; generator context ${q.programLength} instructions. ${c.state.parameters.toLocaleString()} trainable parameters across both models. Backend: ${escape(c.state.backend)}.</p>`;}
 if(!body)return '';return `<section class="live-diagnostic"><h4>Computed from ${r?'this program':c.plot?'this graph point':'this run'} · round ${r?.round??c.plot?.x??c.state?.round??'—'}</h4>${body}<small>Captured when opened; nested explanations keep this same data while training continues.</small></section>`;
}
