import {ARTICLES,CHAPTERS,PREREQUISITES,outgoing,backlinks,titleOf} from './knowledge-data.mjs';
import {ENTRYPOINTS,DYNAMIC_ENTRYPOINTS} from './entrypoints.mjs';
import {diagnosticHTML} from './diagnostics.mjs';
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function link(id,label=titleOf(id)){return `<a href="wiki.html#article=${id}" data-concept="${id}">${escape(label)}</a>`;}
function inline(text){return escape(text).replace(/\[\[([\w-]+)(?:\|([^\]]+))?\]\]/g,(_,id,label)=>link(id,label?label.replace(/&amp;/g,'&'):titleOf(id))).replace(/\*\*([^*]+)\*\*/g,'<strong>$1</strong>');}
export function prose(text){return text.trim().split(/\n\s*\n/).map(p=>p.startsWith('## ')?p.split('\n').map((l,i)=>i===0?`<h3>${inline(l.slice(3))}</h3>`:`<p>${inline(l)}</p>`).join(''):`<p>${inline(p).replace(/\n/g,'<br>')}</p>`).join('');}
let mathPromise,mathQueue=Promise.resolve();
function typeset(node){
 if(!node.textContent.includes('\\'))return;
 if(!mathPromise)mathPromise=new Promise((resolve,reject)=>{window.MathJax={tex:{inlineMath:[['\\(','\\)']],displayMath:[['\\[','\\]']]},svg:{fontCache:'local'},startup:{typeset:false},options:{enableMenu:false}};const s=document.createElement('script');s.src=new URL('./vendor/mathjax-tex-svg-3.2.2.js',import.meta.url).href;s.onload=()=>window.MathJax.startup.promise.then(resolve,reject);s.onerror=reject;document.head.append(s);});
 mathQueue=mathQueue.then(()=>mathPromise).then(()=>node.isConnected?window.MathJax.typesetPromise([node]):null).catch(()=>{node.classList.add('math-fallback');});
}
function clearMath(node){if(window.MathJax?.typesetClear)window.MathJax.typesetClear([node]);}
function articleHTML(id,context){const a=ARTICLES[id];return `<div class="article-kind">${escape(a.kind)} · ${CHAPTERS.find(c=>c.id===a.chapter).title}</div><h2>${escape(a.title)}</h2><p class="article-summary">${inline(a.summary)}</p>${diagnosticHTML(id,context)}${PREREQUISITES[id]?`<p class="prerequisites">Background: ${PREREQUISITES[id].map(x=>link(x)).join(' · ')}</p>`:''}<div class="article-prose">${prose(a.body)}</div><section class="article-related"><h3>Continue exploring</h3>${outgoing(id).map(x=>link(x)).join(' · ')}</section><details class="backlinks"><summary>Linked from ${backlinks(id).length} articles</summary><p>${backlinks(id).map(x=>link(x)).join(' · ')}</p></details><p class="article-source"><a href="https://arxiv.org/html/2609.30063v1#${a.source}" target="_blank" rel="noopener">Read the source section in the paper ↗</a> · <a href="wiki.html#article=${id}" target="_blank" rel="noopener">Permanent companion link ↗</a></p>`;}
export function pathsFromEntries(){const paths=new Map();for(const e of [...ENTRYPOINTS,...DYNAMIC_ENTRYPOINTS])if(!paths.has(e.topic))paths.set(e.topic,[e.topic]);const queue=[...paths.keys()];for(let i=0;i<queue.length;i++)for(const n of outgoing(queue[i]))if(!paths.has(n)){paths.set(n,[...paths.get(queue[i]),n]);queue.push(n);}return paths;}
export function initKnowledge({standalone=false}={}){
 let state=null,inspected=null,chain=[],openTimer,closeTimer,hoverAnchor=null,drawer=null,lastFocus=null;
 document.addEventListener('training-view',e=>state=e.detail);document.addEventListener('inspect-view',e=>inspected=e.detail);
 for(const entry of ENTRYPOINTS)for(const el of document.querySelectorAll(entry.selector)){if(!el.dataset.concept)el.dataset.concept=entry.topic;if(!el.matches('button,input,select,summary,a')&&!el.closest('button')){el.tabIndex=0;el.setAttribute('role','button');}el.setAttribute('aria-haspopup','dialog');}
 for(const el of document.querySelectorAll('[data-concept]')){if(!el.matches('a,button,input,select,summary')&&!el.closest('button,label,summary')&&el.id!=='probe-tabs'&&!el.querySelector('button,input,select')){el.tabIndex=0;el.setAttribute('role','button');}el.setAttribute('aria-haspopup','dialog');}
 for(const a of document.querySelectorAll('a[data-concept]')){a.href=`wiki.html#article=${a.dataset.concept}`;a.setAttribute('aria-haspopup','dialog');}
 function capture(anchor,event){const panel=anchor.closest('.concept-tooltip');if(panel)return chain.find(x=>x.el===panel)?.context;
  const rowEl=anchor.closest('[data-row-index]'),row=rowEl?state?.latest?.rows[Number(rowEl.dataset.rowIndex)]:anchor.closest('#inspector')?inspected?.row:null;
  const context={state:anchor.closest('#inspector')?(inspected?.state??state):state,row,byteIndex:anchor.dataset.byteIndex===undefined?undefined:Number(anchor.dataset.byteIndex)};
  if(anchor._plotData){const p=anchor._plotData,rect=anchor.getBoundingClientRect(),at=Math.max(0,Math.min(1,((event?.clientX??rect.left+rect.width/2)-rect.left-p.left)/(rect.width-p.left-p.right)))*p.maxX;const all=p.series.flatMap(s=>s.data).filter(([x,y])=>Number.isFinite(y));if(all.length){const x=all.reduce((best,a)=>Math.abs(a[0]-at)<Math.abs(best[0]-at)?a:best)[0];const labels=anchor.id==='training-chart'?['Emitted-byte loss','Padding loss']:anchor.id==='probe-chart'||anchor.id==='custom-chart'?['Learner','Random-program control']:['Mean','Mean + stddev','Mean − stddev'];context.plot={x,unit:p.unit,xLabel:p.xLabel,values:p.series.map((s,i)=>({label:labels[i],y:s.data.find(a=>a[0]===x)?.[1]})).filter(x=>Number.isFinite(x.y))};}}
  return context;
 }
 function truncate(depth,focus=false){clearTimeout(closeTimer);const removed=chain.splice(depth);for(const c of removed){clearMath(c.el);c.el.remove();}if(focus)removed[0]?.anchor?.focus?.({preventScroll:true});}
 function place(card,rect,depth){const w=Math.min(440,innerWidth-24),h=Math.min(620,innerHeight-32);card.style.width=w+'px';card.style.maxHeight=h+'px';let x=rect.right+9;if(x+w>innerWidth-12)x=rect.left-w-9;if(x<12)x=Math.min(innerWidth-w-12,24+depth*24);let y=Math.max(12,Math.min(rect.top,innerHeight-h-12));card.style.left=x+'px';card.style.top=y+'px';}
 function openTip(anchor,pinned,event,captured){const id=anchor.dataset.concept;if(!ARTICLES[id])return;const parent=anchor.closest('.concept-tooltip'),depth=parent?chain.findIndex(c=>c.el===parent)+1:0;
  if(!pinned&&depth===0&&chain[0]?.pinned)return;
  if(chain[depth]?.anchor===anchor&&chain[depth]?.id===id){if(pinned){chain[depth].pinned=true;chain[depth].el.querySelector('.pin-tip').textContent='Pinned';}return;}
  const context=captured?.context??capture(anchor,event),rect=captured?.rect??anchor.getBoundingClientRect();truncate(depth);for(const c of chain){c.pinned=true;c.el.querySelector('.pin-tip').textContent='Pinned';}
  const el=document.createElement('section');el.className='concept-tooltip';el.setAttribute('role','dialog');el.setAttribute('aria-label',titleOf(id));el.tabIndex=-1;el.style.zIndex=110+depth;
  const crumbs=[...chain.map(c=>c.id),id];el.innerHTML=`<div class="tip-toolbar"><button class="pin-tip">${pinned?'Pinned':'Keep open'}</button><button class="wiki-tip">Full article</button><button class="close-tip" aria-label="Close ${escape(titleOf(id))}">×</button></div><div class="tip-trail">${crumbs.map((x,i)=>`<button data-depth="${i}" ${i===depth?'aria-current="page"':''}>${i+1} · ${escape(titleOf(x))}</button>`).join('<span>›</span>')}</div><div class="tip-content">${articleHTML(id,context)}</div>`;
  const c={el,id,anchor,pinned,context};chain.push(c);document.body.append(el);place(el,rect,depth);typeset(el);
  el.querySelector('.pin-tip').onclick=()=>{c.pinned=true;el.querySelector('.pin-tip').textContent='Pinned';};el.querySelector('.close-tip').onclick=()=>truncate(depth,true);el.querySelector('.wiki-tip').onclick=()=>{truncate(0);showWiki(id);};
  el.querySelectorAll('[data-depth]').forEach(b=>b.onclick=()=>{const n=Number(b.dataset.depth);truncate(n+1);chain[n]?.el.focus();});
  el.addEventListener('pointerenter',()=>{clearTimeout(closeTimer);});el.addEventListener('pointerleave',()=>scheduleClose());
  if(pinned)el.focus({preventScroll:true});
 }
 function scheduleClose(){clearTimeout(closeTimer);closeTimer=setTimeout(()=>{const first=chain.findIndex(c=>!c.pinned&&!c.el.matches(':hover'));if(first>=0)truncate(first);},550);}
 document.addEventListener('pointerover',event=>{const anchor=event.target.closest('[data-concept]');if(!anchor||anchor===hoverAnchor)return;hoverAnchor=anchor;clearTimeout(openTimer);clearTimeout(closeTimer);const captured={context:capture(anchor,event),rect:anchor.getBoundingClientRect()};openTimer=setTimeout(()=>openTip(anchor,false,event,captured),anchor.closest('.concept-tooltip')?450:650);});
 document.addEventListener('pointerout',event=>{const anchor=event.target.closest('[data-concept]');if(anchor&&!anchor.contains(event.relatedTarget)){hoverAnchor=null;clearTimeout(openTimer);scheduleClose();}});
 document.addEventListener('click',event=>{const anchor=event.target.closest('[data-concept]');if(!anchor)return;if(anchor.matches('input,select,summary')||anchor.closest('summary')||anchor.closest('#probe-tabs')||anchor.closest('.options label')||anchor.closest('.program-row'))return;event.preventDefault();clearTimeout(openTimer);openTip(anchor,true,event);});
 document.addEventListener('keydown',event=>{if(event.key==='Escape'){if(chain.length){event.preventDefault();truncate(chain.length-1,true);}else if(drawer&&!standalone)closeWiki();}else if(event.key==='Enter'&&event.target.matches('[data-concept]:not(a):not(button):not(summary)')){event.preventDefault();openTip(event.target,true,event);}});
 window.addEventListener('resize',()=>{for(let i=0;i<chain.length;i++)place(chain[i].el,chain[i].anchor.isConnected?chain[i].anchor.getBoundingClientRect():{left:20,top:20,right:40},i);});
 function closeWiki(){if(!drawer)return;clearMath(drawer);drawer.remove();drawer=null;document.body.classList.remove('wiki-open');lastFocus?.focus();}
 function showWiki(id='overview'){
  if(!drawer){lastFocus=document.activeElement;drawer=document.createElement('section');drawer.className='wiki-drawer'+(standalone?' standalone':'');drawer.setAttribute('role','dialog');drawer.setAttribute('aria-label','Paper companion');drawer.innerHTML=`<header class="wiki-header"><div><b>Self-play · Paper companion</b><small>${Object.keys(ARTICLES).length} connected explanations · source sections linked throughout</small></div>${standalone?'<a href="./">← Playground</a>':'<button class="wiki-close">Close companion ×</button>'}</header><div class="wiki-layout"><aside class="wiki-nav"><label>Find a concept<input type="search" placeholder="Reward, attention, scaling…" aria-label="Find a concept"></label><div class="wiki-views"><button data-view="overview">Read</button><button data-view="map">Concept map</button><button data-view="entrypoints">UI entrypoints</button></div><div class="wiki-index"></div></aside><article class="wiki-content" tabindex="-1"></article></div>`;document.body.append(drawer);document.body.classList.add('wiki-open');drawer.querySelector('.wiki-close')?.addEventListener('click',closeWiki);drawer.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>showWiki(b.dataset.view));drawer.querySelector('input').oninput=()=>drawIndex(drawer.querySelector('input').value);drawIndex('');}
  const content=drawer.querySelector('.wiki-content');clearMath(content);
  if(id==='map')content.innerHTML=mapHTML();else if(id==='entrypoints')content.innerHTML=entriesHTML();else{if(!ARTICLES[id])id='overview';content.innerHTML=articleHTML(id,null);}
  content.scrollTop=0;typeset(content);if(standalone)history.replaceState(null,'',id==='map'||id==='entrypoints'?'#'+id:'#article='+id);
  // In the full wiki, article links navigate on click and still open nested previews on hover.
  content.querySelectorAll('[data-concept]').forEach(a=>a.addEventListener('click',e=>{e.stopPropagation();e.preventDefault();truncate(0);showWiki(a.dataset.concept);}));
  content.querySelectorAll('[data-locate]').forEach(b=>b.onclick=()=>{const entry=[...ENTRYPOINTS,...DYNAMIC_ENTRYPOINTS][Number(b.dataset.locate)];if(standalone){location.href='./#locate='+encodeURIComponent(entry.selector);return;}closeWiki();locate(entry.selector);});
  content.querySelectorAll('[data-map-select]').forEach(b=>b.onclick=()=>drawNeighbors(b.dataset.mapSelect));
  if(id==='map')drawNeighbors('gradient-reward');content.focus({preventScroll:true});
 }
 function drawIndex(query){const q=query.toLowerCase(),index=drawer.querySelector('.wiki-index');index.innerHTML=CHAPTERS.map(c=>{const entries=Object.values(ARTICLES).filter(a=>a.chapter===c.id&&(!q||[a.title,a.summary,a.body].join(' ').toLowerCase().includes(q)));return entries.length?`<h3>${c.title}</h3>${entries.map(a=>`<button data-article="${a.id}">${escape(a.title)}</button>`).join('')}`:'';}).join('')||'<p>No matching concepts.</p>';index.querySelectorAll('button').forEach(b=>b.onclick=()=>showWiki(b.dataset.article));}
 function mapHTML(){const count=Object.keys(ARTICLES).length,edges=Object.keys(ARTICLES).reduce((n,id)=>n+outgoing(id).length,0),paths=pathsFromEntries();return `<h2>Concept map</h2><p>${count} articles · ${edges} directed connections · ${paths.size}/${count} reachable from playground entrypoints. Select a concept to see its incoming and outgoing links. Chapter cards below provide a separate map of the paper.</p><div id="map-neighbors"></div><div class="chapter-map">${CHAPTERS.map(c=>`<section><h3>${c.title}</h3>${Object.values(ARTICLES).filter(a=>a.chapter===c.id).map(a=>`<button data-map-select="${a.id}">${escape(a.title)}</button>`).join('')}</section>`).join('')}</div>`;}
 function drawNeighbors(id){const host=drawer.querySelector('#map-neighbors');host.innerHTML=`<div class="neighbor-map"><section><h3>Explained by / linked from</h3>${backlinks(id).map(x=>`<button data-neighbor="${x}">${escape(titleOf(x))}</button>`).join('')}</section><section class="map-selected"><span>Selected concept</span><h3>${escape(titleOf(id))}</h3><p>${escape(ARTICLES[id].summary)}</p><button id="read-map-article">Read article</button></section><section><h3>Connects to →</h3>${outgoing(id).map(x=>`<button data-neighbor="${x}">${escape(titleOf(x))}</button>`).join('')}</section></div>`;host.querySelectorAll('[data-neighbor]').forEach(b=>b.onclick=()=>drawNeighbors(b.dataset.neighbor));host.querySelector('#read-map-article').onclick=()=>showWiki(id);}
 function entriesHTML(){const entries=[...ENTRYPOINTS,...DYNAMIC_ENTRYPOINTS],paths=pathsFromEntries();return `<h2>Playground entrypoints</h2><p>This maps the controls and data you can hover or focus to the first explanation they open. Links within each explanation lead into the separate article graph. Generated rows appear after the first training round.</p><table><thead><tr><th>Where to begin</th><th>First explanation</th><th>Location</th></tr></thead><tbody>${entries.map((e,i)=>`<tr><td>${escape(e.label)}</td><td>${link(e.topic)}</td><td><button data-locate="${i}">Show in playground</button></td></tr>`).join('')}</tbody></table><h3>Shortest reading paths from the interface</h3><p>Every article has a route from at least one real UI entrypoint. These are shortest directed paths; related links and backlinks provide additional routes.</p>${Object.values(ARTICLES).map(a=>`<p class="reading-path">${(paths.get(a.id)??[]).map(x=>link(x)).join(' → ')}</p>`).join('')}`;}
 function locate(selector){const el=document.querySelector(selector);if(!el)return;for(let p=el.parentElement;p;p=p.parentElement)if(p.tagName==='DETAILS')p.open=true;el.scrollIntoView({behavior:'smooth',block:'center'});el.classList.add('attention-result');setTimeout(()=>el.classList.remove('attention-result'),2500);el.focus?.({preventScroll:true});}
 document.getElementById('open-wiki')?.addEventListener('click',()=>showWiki());document.getElementById('open-map')?.addEventListener('click',()=>showWiki('map'));
 function hash(){const value=decodeURIComponent(location.hash.slice(1));if(value.startsWith('locate=')){locate(value.slice(7));return;}if(standalone||value.startsWith('article=')||['map','entrypoints'].includes(value))showWiki(value.startsWith('article=')?value.slice(8):value||'overview');}
 window.addEventListener('hashchange',hash);hash();return {showWiki};
}
